name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t my-app:latest .

    - name: Run Docker container (Local Testing)
      run: |
        docker run -d -p 8080:80 --name my-app-container my-app:latest
        sleep 10  # Wait for the container to start
        curl http://localhost:8080  # Test the app locally
        docker stop my-app-container  # Stop the container after testing
        docker rm my-app-container  # Clean up the container

#    - name: Set up kubectl
#      uses: azure/setup-kubectl@v3
#      with:
#        version: 'latest'

#    - name: Configure Kubeconfig
#      run: |
#        echo "${{ secrets.KUBECONFIG }}" > kubeconfig
#        export KUBECONFIG=$PWD/kubeconfig

#    - name: Deploy to Kubernetes
#      run: kubectl apply -f k8s/deployment.yaml
